"""change completed_at -> updated_at

Revision ID: 2c6c244819c0
Revises: 3406820f7a06
Create Date: 2025-07-20 10:15:08.324949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c6c244819c0'
down_revision: Union[str, Sequence[str], None] = '3406820f7a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('orders', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('completed_at', mysql.DATETIME(), nullable=True))
    op.drop_column('orders', 'updated_at')
    # ### end Alembic commands ###
