"""Add completed at field to orders

Revision ID: 3406820f7a06
Revises: d9b0e9a92cef
Create Date: 2025-07-20 10:14:23.907731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3406820f7a06'
down_revision: Union[str, Sequence[str], None] = 'd9b0e9a92cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'completed_at')
    # ### end Alembic commands ###
